movierecommender/Models/Movie.cs
namespace movierecommender.Models
{
    public class Movie
    {
        public int MovieID { get; set; }
        public string MovieName { get; set; }
    }    
}

movierecommender/Models/MovieService.cs
using CsvHelper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;

namespace movierecommender.Models
{
    public partial class MovieService
    {
        public readonly static int _moviesToRecommend = 6;
        public Lazy<List<Movie>> _movies = new Lazy<List<Movie>>(() => LoadMovieData());

        public IEnumerable<Movie> GetSomeSuggestions()
        {
            var movies = GetRecentMovies().ToArray();

            Random rnd = new Random();
            int[] movieselector = new int[_moviesToRecommend];
            for (int i = 0; i < _moviesToRecommend; i++)
            {
                movieselector[i] = rnd.Next(movies.Length);
            }

            return movieselector.Select(s => movies[s]);
        }

        public IEnumerable<Movie> GetRecentMovies()
        {
            return GetAllMovies()
                .Where(m => m.MovieName.Contains("20")
                            || m.MovieName.Contains("198")
                            || m.MovieName.Contains("199"));
        }

        public Movie Get(int id)
        {
            return _movies.Value.Single(m => m.MovieID == id);
        }


        public IEnumerable<Movie> GetAllMovies()
        {
            return _movies.Value;
        }

        private static List<Movie> LoadMovieData()
        {
            var result = new List<Movie>();

            // Use this for the 20M dataset. 
            //Stream fileReader = File.OpenRead("Content/MovieLens 20M dataset _movies.csv");

            Stream fileReader = File.OpenRead("Content/MovieLens 1M dataset _movies.csv");
            StreamReader reader = new StreamReader(fileReader);
            try
            {
                bool header = true;
                int index = 0;
                var line = "";
                while (!reader.EndOfStream)
                {
                    if (header)
                    {
                        line = reader.ReadLine();
                        header = false;
                    }
                    line = reader.ReadLine();
                    string[] fields = line.Split(',');
                    int MovieID = Int32.Parse(fields[0].ToString().TrimStart(new char[] { '0' }));
                    string MovieName = fields[1].ToString();
                    result.Add(new Movie() { MovieID = MovieID, MovieName = MovieName });
                    index++;
                }
            }
            finally
            {
                if (reader != null)
                {
                    reader.Dispose(); 
                }
            }

            return result;
        }
    }
}

movierecommender/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using movierecommender.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;

namespace movierecommender.Controllers
{
    public class StringTable
    {
        public string[] ColumnNames { get; set; }
        public string[,] Values { get; set; }
    }

    public class MoviesController : Controller
    {
        private readonly MovieService _movieService;
        private readonly AppSettings _appSettings;
        //private static HttpClient Client = new HttpClient();
        private readonly ILogger<MoviesController> _logger;

        public MoviesController(MovieService movieService, ILogger<MoviesController> logger, IOptions<AppSettings> appSettings)
        {
            _movieService = movieService;
            _logger = logger;
            _appSettings = appSettings.Value;
        }

        public ActionResult Choose()
        {
            return View(_movieService.GetSomeSuggestions());
        }

        static async Task<string> InvokeRequestResponseService(int id, ILogger logger, AppSettings appSettings)
        {
            using (var client = new HttpClient())
            {
                var scoreRequest = new
                {

                    Inputs = new Dictionary<string, StringTable>() {
                        {
                            "input1",
                            new StringTable()
                            {
                                ColumnNames = new string[] {"UserID", "MovieID", "Rating"},
                                Values = new string[,] {  { "0", id.ToString(), "5" } }
                            }
                        },
                    },
                    GlobalParameters = new Dictionary<string, string>()
                    {
                    }
                };

                string apiKey = appSettings.apikey;
                string uri = appSettings.uri; 
                if (apiKey != string.Empty && uri != string.Empty)
                {
                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", apiKey);
                    client.BaseAddress = new Uri(uri);

                    HttpResponseMessage response = await client.PostAsync(appSettings.uri, new JsonContent(scoreRequest));

                    if (response.IsSuccessStatusCode)
                    {
                        string result = await response.Content.ReadAsStringAsync();
                        return result;
                    }
                    else
                    {
                        logger.LogError(string.Format("The request failed with status code: {0}", response.StatusCode));
                        // Print the headers - they include the requert ID and the timestamp,
                        // which are useful for debugging the failure
                        logger.LogDebug(response.Headers.ToString());

                        string responseContent = await response.Content.ReadAsStringAsync();
                        logger.LogDebug(responseContent);
                        return null;
                    }
                } else
                {
                    logger.LogError("Please provide apiKey and URI to the Machine Learning WebService");
                }

                return null; 
        }
}

        public async Task<ActionResult> Recommend(int id)
        {
            try
            {
                var result = await InvokeRequestResponseService(id, _logger, _appSettings);
                var obj = JObject.Parse(result);
                var suggestedMovies = obj["Results"]["output1"]["value"]["Values"][0]
                        .Select(i => i.Value<string>())
                        .Select(i => int.Parse(i))
                        .Select(i => _movieService.Get(i));
                return View(suggestedMovies);
            }
            catch (Exception e)
            {
                _logger.LogError(string.Format("An error occured:'{0}'", e));
                return View(); 
            }
         }

        public ActionResult Watch()
        {
            return View();
        }

        public class JsonContent : StringContent
        {
            public JsonContent(object obj) :
                base(JsonConvert.SerializeObject(obj), Encoding.UTF8, "application/json")
            { }
        }
    }
}

movierecommender/Views/Movies/Choose.cshtml
@using movierecommender.Models
@model  IEnumerable<Movie>
@{
    ViewBag.Title = "Choose";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Movie Recommender</h1>

<h3>Pick the movie you best liked in the past?</h3>

    <div class="row">
        @foreach (var movie in Model)
        {
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-block">
                        <h3 class="card-title">@movie.MovieName</h3>
                        <a href="@Url.Action("Recommend", "Movies", new { id = movie.MovieID })" class="btn btn-primary">Choose me</a>
                    </div>
                </div>
            </div>
        }
    </div>

    <hr />
    <button type="button" OnClick="location.href='@Url.Action("Choose", "Movies")'" class="btn btn-lg breadcrumb btn-link">Haven't seen these movies, Try again!</button> 

movierecommender/Views/Movies/Recommend.cshtml
@using movierecommender.Models
@model  IEnumerable<Movie>
@{
    ViewBag.Title = "Recommend";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>A few recommendations!</h1>

<div class="row">
    @if (Model != null)
    {
        foreach (var movie in Model)
        {
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-block">
                        <h3 class="card-title">@movie.MovieName</h3>
                        <a href="@Url.Action("Watch", "Movies")" class="btn btn-primary">Play Movie</a>
                    </div>
                </div>
            </div>
        }
    }
    else
    {
        <h2>Something went wrong! please check the error log.</h2>
    }
    </div>
<hr />
<button type="button" OnClick="location.href='@Url.Action("Choose", "Movies")'" class="btn btn-lg breadcrumb btn-link">This is fun, Let Me Try Again!</button>

movierecommender/Views/Movies/Watch.cshtml
@{
    ViewBag.Title = "Watch";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>That's as far as this gets today!</h1>

movierecommender/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - movierecommender</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - movierecommender</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>